import type { Metadata } from "next";
import { Providers } from "./providers";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import Script from "next/script"; // ✅ added import

export const metadata: Metadata = {
    title: "My App",
    description: "Generated by Next.js with Chakra UI",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        {/* ✅ HubSpot Tracking + Chat Script */}
        <Script
            id="hubspot-tracking"
            strategy="afterInteractive"
            src="//js.hs-scripts.com/244234761.js"
        />

        <Providers>
            <Header />
            {children}
            <Footer />
        </Providers>
        </body>
        </html>
    );
}
