import type { Metadata } from "next";
import { Providers } from "./providers";
import Header from '../components/Header'
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js with Chakra UI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <Header /> 
          {children}
          <Footer />
          </Providers>
      </body>
    </html>
  );
}
